### ISSUE TITLE
"More like this" is missing

### ISSUE THREAD

**Issue by eyecreate** [dbalz3/SuperSteam_Firefox#5]
The more like this section of the store pages is missing with this extension enabled. Would be nice if it didn't get lost.
![oops3](https://cloud.githubusercontent.com/assets/227856/21949099/906e900a-d9bd-11e6-80ba-ebc05a1a2d44.png)

**Comment by cprn** [comment]
Works for me:

![2017-04-26-233517_881x780_scrot](https://cloud.githubusercontent.com/assets/6132708/25458136/08b12bd8-2ad9-11e7-9a26-7d2c8f55fd59.png)

**Comment by eyecreate** [comment]
I've had trouble recreating it myself recently. Will reopen if I see it again.
